ALTER TABLE user_habit
ADD COLUMN frequency VARCHAR(20) NOT NULL DEFAULT 'DAILY',
ADD COLUMN start_date DATE NOT NULL DEFAULT (CURRENT_DATE);

ALTER TABLE habit MODIFY COLUMN is_public BOOLEAN;
ALTER TABLE category MODIFY COLUMN is_active BOOLEAN;