spring:
  application:
    name: just-do-today

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: just_do_today

springdoc:
  packages-to-scan: com.example.just_do_today.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

logging:
  level:
    org.flywaydb: DEBUG

#소셜로그인 - 카카오
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

app:
  oauth-success-redirect: ${OAUTH_SUCCESS_REDIRECT}
  jwt:
    secret: ${JWT_SECRET}
    access-exp-min: 60
